### ISSUE TITLE
Does this work, anymore?

### ISSUE THREAD

**Issue by joe733** [dave/youtube#1]
![Screenshot from 2021-02-02 20-09-42](https://user-images.githubusercontent.com/38415384/106615641-a868c080-6592-11eb-9179-c7383f70cd35.png)

Since this action is no longer possible from UI, does this method work anymore?

**Comment by dave** [comment]
This project was created for a specific task so it's not something I'll be updating... However, it didn't rely on any magic to transfer the videos from Google Drive to Youtube... It [used the Google Drive API to read the files](https://github.com/dave/youtube/blob/master/main.go#L235), and the [Youtube API to upload the files](https://github.com/dave/youtube/blob/master/main.go#L239)... So I don't see any reason it wouldn't still work.
